spring.application.name=api
server.port = 8090
spring.datasource.url = jdbc:postgresql://localhost:5432/TBD_LAB1
spring.datasource.username=postgres
spring.datasource.password=Claire12261510
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=never
jwt.secret=$2a$10$kKBlJYCM1FrHLd1ESc2Q/OoK5jfNSMr/gjVRzSJeFVrZcmtaXEPVW
jwt.expiration=3600000